namespace: yoctoalex
name: xc_cloud_modules
version: 0.0.5
readme: README.md
authors:
  - Alex Shemyakin
description: Collection to manage XC Cloud
license: GPL-3.0-only
tags:
  - f5
  - cloud
  - f5_distributed_cloud_services
  - f5_distributed_cloud
  - f5_cloud
repository: https://github.com/yoctoalex/xc-cloud-ansible
documentation: https://github.com/yoctoalex/xc-cloud-ansible
homepage: https://github.com/yoctoalex/xc-cloud-ansible
issues: https://github.com/yoctoalex/xc-cloud-ansible/issues
dependencies:
  ansible.netcommon: ">=2.0.0"